apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: cluster
  namespace: cluster
spec:
  clusterRef:
    name: cluster
    namespace: cluster

  pullSecretRef:
    name: pull-secret

  sshAuthorizedKey: "<YOUR_SSH_PUBLIC_KEY>"

  nmStateConfigLabelSelector:
    matchLabels:
      cluster: cluster
