apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentclusterinstall.yaml
  - clusterdeployment.yaml
  - infraenv.yaml
  - managedcluster.yaml
  - klusterletaddonconfig.yaml
