apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault-hub-sa.yaml
  - vault-hub-role.yaml
  - vault-hub-rolebinding.yaml
  - vault-hub-configmap.yaml
  - vault-hub-job.yaml
