# 1/4 - HUB: OpenShift pull secret
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pull-secret
  namespace: cluster
spec:
  vaultAuthRef: provisioning-vault-auth
  mount: acm
  type: kv-v2
  path: cluster/pull-secret
  refreshAfter: 1h
  destination:
    name: pull-secret
    create: true
    overwrite: true
    type: kubernetes.io/dockerconfigjson
---
# 2/4 - HUB: shared BMC/Redfish credentials for the cluster's BMHs
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bmc-credentials
  namespace: cluster
spec:
  vaultAuthRef: provisioning-vault-auth
  mount: acm
  type: kv-v2
  path: cluster/bmc
  refreshAfter: 1h
  destination:
    name: bmc-credentials
    create: true
    overwrite: true
    type: Opaque
---
# 3/4 - HUB: narrowly scoped Vault bootstrap token for the post-install Job
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-bootstrap-credentials
  namespace: cluster
spec:
  vaultAuthRef: provisioning-vault-auth
  mount: acm
  type: kv-v2
  path: cluster/vault-bootstrap
  refreshAfter: 1h
  destination:
    name: vault-bootstrap-credentials
    create: true
    overwrite: true
    type: Opaque
