apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: ove604m1
  namespace: ove604a
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: ove604m1
    bmac.agent-install.openshift.io/role: master
  labels:
    infraenvs.agent-install.openshift.io: ove604a
spec:
  online: true
  bootMode: UEFI
  bootMACAddress: "00:50:56:ab:c3:c7"
  bmc:
    address: "redfish-virtualmedia://192.168.1.183:8000/redfish/v1/Systems/422bbe08-4149-0286-b95e-d29542fd7540"
    credentialsName: bmc-credentials
    disableCertificateVerification: true
  automatedCleaningMode: disabled
