apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: ove604m3
  namespace: ove604a
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: ove604m3
    bmac.agent-install.openshift.io/role: master
  labels:
    infraenvs.agent-install.openshift.io: ove604a
spec:
  online: true
  bootMode: UEFI
  bootMACAddress: "00:50:56:ab:5c:17"
  bmc:
    address: "redfish-virtualmedia://192.168.1.183:8000/redfish/v1/Systems/422b4e8c-a385-7a2b-fc2c-c4c77fe69d80"
    credentialsName: bmc-credentials
    disableCertificateVerification: true
  automatedCleaningMode: disabled
