apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: ove604m2
  namespace: ove604a
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: ove604m2
    bmac.agent-install.openshift.io/role: master
  labels:
    infraenvs.agent-install.openshift.io: ove604a
spec:
  online: true
  bootMode: UEFI
  bootMACAddress: "00:50:56:ab:6e:1e"
  bmc:
    address: "redfish-virtualmedia://192.168.1.183:8000/redfish/v1/Systems/422b65f8-bda6-a897-5f2f-fad0dabdef0a"
    credentialsName: bmc-credentials
    disableCertificateVerification: true
  automatedCleaningMode: disabled
