apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: ove604w3
  namespace: ove604a
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: ove604w3
    bmac.agent-install.openshift.io/role: worker
  labels:
    infraenvs.agent-install.openshift.io: ove604a
spec:
  online: true
  bootMode: UEFI
  bootMACAddress: "00:50:56:ab:56:96"
  bmc:
    address: "redfish-virtualmedia://192.168.1.183:8000/redfish/v1/Systems/422b6438-1dc4-c193-3a59-2c37d44aebd3"
    credentialsName: bmc-credentials
    disableCertificateVerification: true
  automatedCleaningMode: disabled
