apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: ove604w1
  namespace: ove604a
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: ove604w1
    bmac.agent-install.openshift.io/role: worker
  labels:
    infraenvs.agent-install.openshift.io: ove604a
spec:
  online: true
  bootMode: UEFI
  bootMACAddress: "00:50:56:ab:ef:44"
  bmc:
    address: "redfish-virtualmedia://192.168.1.183:8000/redfish/v1/Systems/422bbe5a-f3b5-1103-21a3-2e90f280bf2a"
    credentialsName: bmc-credentials
    disableCertificateVerification: true
  automatedCleaningMode: disabled
